spring:
  datasource:
    url: jdbc:mysql://172.24.211.113:3306/example_db?allowMultiQueries=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 'root'
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 172.24.211.113
      port: 6379
      password: '111111'
      database: 0
  mvc:
    static-path-pattern: '/static/**'
  main:
    allow-circular-references: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: 'classpath*:/**/*Mapper.xml'

# token 相关配置
token:
  secret: '0nJ7/jp48ebg4K0B4EMYog==' # token 密钥
  expire: 86400000 # token 过期时间
  key: 'Authorization' # token 请求头名称

# 数据库 AES 加密配置
db-aes-key: 'CGjbN1QmsU2TYDiuiy5Zsg=='

aes-key: 'Ojj5FNlpl9HY1lqiTebZWQ=='

# xss 配置
xss:
  enable: true
  excludes: ~
